name = "TensorContractionsXD"
uuid = "2200dae6-05f0-40f4-9fe9-6ee0acf43bbd"
authors = ["PhysicsCodesLab"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StridedTensorXD = "264d0366-5c21-4846-9aa6-f0da616294d5"
TupleLabXD = "dd89015c-70e0-43f5-a84b-ae32a3a24356"

[compat]
CUDA = "1-2"
LRUCache = "1"
Requires = "0.5,1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
