name = "TensorOperationsXD"
uuid = "2200dae6-05f0-40f4-9fe9-6ee0acf43bbd"
authors = ["PhysicsCodesLab"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Strided = "5e0ebb24-38b0-5f93-81fe-25c709ecae67"
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"

[compat]
CUDA = "3.2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
